apiVersion: v1
kind: Service
metadata:
  name: piraeus-api
  namespace: kube-system
  labels:
    app.kubernetes.io/name: piraeus
    app.kubernetes.io/component: piraeus-controller
spec:
  type: NodePort
  ports:
  - name: rest-api
    port: 3370
    targetPort: 3370
    nodePort: 30370
  selector:
    app.kubernetes.io/name: piraeus
    app.kubernetes.io/component: piraeus-controller