apiVersion: v1
kind: ConfigMap
metadata:
  name: piraeus-scaler
  namespace: piraeus-system
data:
  INIT_DEBUG: "false"
  LS_CONTROLLERS: piraeus-controller.piraeus-system.svc.cluster.local:3370
  POOL_BASE_DIR: /var/lib/piraeus/storagepools
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: piraeus-scaler
  namespace: piraeus-system
spec:
  minReadySeconds: 0
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: piraeus
      app.kubernetes.io/component: piraeus-scaler
  template:
    metadata:
      labels:
        app.kubernetes.io/name: piraeus
        app.kubernetes.io/component: piraeus-scaler
    spec:
      restartPolicy: Always
      hostNetwork: true
      hostPID: true
      hostIPC: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: tasker
        image: quay.io/piraeusdatastore/piraeus-init:v0.5.3
        imagePullPolicy: Always
        securityContext:
          privileged: true
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
        envFrom:
        - configMapRef:
            name: piraeus-scaler
        env:
        - name: THIS_POD_UID
          valueFrom:
            fieldRef:
              fieldPath: metadata.uid
        - name: THIS_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: THIS_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        args:
        - initScaler
        readinessProbe:
          successThreshold: 3
          failureThreshold: 3
          httpGet:
            port: 13366
          periodSeconds: 1
        volumeMounts:
        - name: localtime
          mountPath: /etc/localtime
        - name: dockersock
          mountPath: /var/run/docker.sock
        - name: usr-src
          mountPath: /usr/src
        - name: lib-modules
          mountPath: /lib/modules
      volumes:
      - name: localtime
        hostPath:
          path: /etc/localtime
      - name: var-local-piraeus
        hostPath:
          path: /var/local/piraeus
      - name: dev
        hostPath:
          path: /dev
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock
          type: Socket
      - name: usr-src
        hostPath:
          path: /usr/src
      - name: lib-modules
        hostPath:
          path: /lib/modules
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: piraeus/node
                operator: In
                values:
                - "true"
              - key: node-role.kubernetes.io/master
                operator: DoesNotExist
      tolerations:
      - operator: Exists
        effect: NoSchedule
      - key: CriticalAddonsOnly
        operator: Exists
