apiVersion: v1
kind: ConfigMap
metadata:
  name: piraeus-api
  namespace: kube-system
data:
  LS_CONTROLLERS: piraeus-controller.kube-system.svc.cluster.local:3370
  FRONTEND_PORT: "3370"
  HAPROXY_CFG: |
    defaults
        timeout connect 10s
        timeout client 30s
        timeout server 30s
        log stderr format raw daemon notice
        mode tcp
        option tcplog
        maxconn 3000
    frontend node
        bind "${FRONTEND_IP}":"${FRONTEND_PORT}"
        default_backend controllers
    resolvers hostdns
        parse-resolv-conf
        accepted_payload_size 1024
        hold valid 10s
    backend controllers
        balance roundrobin
        server-template controller 1 "${LS_CONTROLLERS}" check resolvers hostdns init-addr none
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: piraeus-api
  namespace: kube-system
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app.kubernetes.io/name: piraeus
      app.kubernetes.io/component: piraeus-api
  template:
    metadata:
      labels:
        app.kubernetes.io/name: piraeus
        app.kubernetes.io/component: piraeus-api
    spec:
      priorityClassName: system-node-critical
      restartPolicy: Always
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: proxy
        image: docker.io/library/haproxy:2.1.3-alpine
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 200m
            memory: 200Mi
        envFrom:
        - configMapRef:
            name: piraeus-api
        env:
        - name: FRONTEND_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        readinessProbe:
          successThreshold: 3
          failureThreshold: 3
          httpGet:
            port: 3370
          initialDelaySeconds: 1
          periodSeconds: 1
        volumeMounts:
        - name: localtime
          mountPath: /etc/localtime
        - name: etc-haproxy
          mountPath: /usr/local/etc/haproxy
      volumes:
      - name: localtime
        hostPath:
          path: /etc/localtime
      - name: etc-haproxy
        configMap:
          name: piraeus-api
          items:
          - key: HAPROXY_CFG
            path: haproxy.cfg
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app.kubernetes.io/component
                operator: In
                values:
                - piraeus-api
            topologyKey: kubernetes.io/hostname
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: piraeus/node
                operator: In
                values:
                - "true"
              - key: node-role.kubernetes.io/master
                operator: DoesNotExist
      tolerations:
      - operator: Exists
        effect: NoSchedule
