apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: piraeus-default-r1
provisioner: linstor.csi.linbit.com
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
parameters:
  layerlist: drbd storage
  placementCount: "1"
  placementPolicy: FollowTopology
  allowRemoteVolumeAccess: "false"
  disklessOnRemaining: "false"
  mountOpts: noatime,discard
  storagePool: DfltStorPool
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: piraeus-default-r2
provisioner: linstor.csi.linbit.com
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
parameters:
  layerlist: drbd storage
  placementCount: "2"
  placementPolicy: FollowTopology
  allowRemoteVolumeAccess: "false"
  disklessOnRemaining: "false"
  mountOpts: noatime,discard
  storagePool: DfltStorPool
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: piraeus-default-r3
provisioner: linstor.csi.linbit.com
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
parameters:
  layerlist: drbd storage
  placementCount: "3"
  placementPolicy: FollowTopology
  allowRemoteVolumeAccess: "false"
  disklessOnRemaining: "false"
  mountOpts: noatime,discard
  storagePool: DfltStorPool
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: piraeus-default-raw
provisioner: linstor.csi.linbit.com
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
parameters:
  layerlist: storage
  placementCount: "1"
  placementPolicy: FollowTopology
  allowRemoteVolumeAccess: "false"
  disklessOnRemaining: "false"
  mountOpts: noatime,discard
  storagePool: DfltStorPool
