---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: piraeus-node
  namespace: piraeus
spec:
  minReadySeconds: 0
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: piraeus
      app.kubernetes.io/component: piraeus-node
  template:
    metadata:
      labels:
        app.kubernetes.io/name: piraeus
        app.kubernetes.io/component: piraeus-node
    spec:
      priorityClassName: system-node-critical
      restartPolicy: Always
      terminationGracePeriodSeconds: 0
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      initContainers:
        - name: init
          image: alexzhc/piraeus-init
          imagePullPolicy: Always
          resources:
            # requests:
            #   cpu: 50m
            #   memory: 50Mi
            limits:
              cpu: 100m
              memory: 100Mi
          env:
            - name: THIS_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name  
            - name: THIS_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP     
            - name: THIS_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName 
            - name: LS_CONTROLLERS
              value: piraeus-controller.piraeus:3370
            - name: DfltStorPool_Dir
              value: /var/local/piraeus/pools/DfltStorPool
            - name: TIMEOUT
              value: '3600'
          args:
            - startSatellite
          volumeMounts:
            - name: localtime
              mountPath: /etc/localtime 
            - name: init
              mountPath: /init
      containers:
        - name: node
          image: quay.io/piraeusdatastore/piraeus-server:v1.3.1
          imagePullPolicy: Always
          securityContext:
            privileged: true
          resources:
            # requests:
            #   cpu: '500m'
            #   memory: '500Mi'
            limits:
              cpu: 1
              memory: 1Gi
          args:
            - startSatellite
          readinessProbe:
            successThreshold: 3
            failureThreshold: 3
            tcpSocket:
              port: 3366
            initialDelaySeconds: 5
            periodSeconds: 1                 
          volumeMounts:        
            - name: localtime
              mountPath: /etc/localtime
            - name: init
              mountPath: /init
            - name: log
              mountPath: /var/log/linstor-satellite
            - name: var-local-piraeus
              mountPath: /var/local/piraeus
            - name: dev
              mountPath: /dev
            - name: lib-modules
              mountPath: /lib/modules
            - name: etc-lvm
              mountPath: /etc/lvm    
            - name: run-lvm
              mountPath: /run/lvm
            - name: etc-drbd-d
              mountPath: /etc/drbd.d
            - name: var-lib-linstor-d
              mountPath: /var/lib/linstor.d
            - name: etc-linstor
              mountPath: /etc/linstor
      volumes:
        - name: localtime
          hostPath:
            path: /etc/localtime
        - name: init
          emptyDir: {}
        - name: log
          hostPath: 
            path: /var/log/piraeus/linstor-satellite
        - name: var-local-piraeus
          hostPath:
            path: /var/local/piraeus
        - name: dev
          hostPath: 
            path: /dev
        - name: usr-sbin
          hostPath:
            path: /usr/sbin
        - name: lib-modules
          hostPath: 
            path: /lib/modules
        - name: etc-lvm
          hostPath: 
            path: /etc/lvm
        - name: run-lvm
          hostPath: 
            path: /run/lvm
        - name: etc-drbd-d
          hostPath: 
            path: /etc/drbd.d
        - name: var-lib-linstor-d
          hostPath: 
            path: /var/lib/linstor.d
        - name: etc-linstor
          hostPath: 
            path: /etc/linstor      
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: piraeus/node
                  operator: In
                  values:
                    - "true"
                - key: node-role.kubernetes.io/master
                  operator: DoesNotExist
      tolerations:
        - operator: "Exists"
          effect: "NoSchedule"