#@ load("funcs.lib.yml", "name", "controller", "initimage", "etcdendpoint", "controllerimage")
apiVersion: v1
kind: ConfigMap
metadata:
  name: #@ controller()
  namespace: kube-system
data:
  INIT_DEBUG: 'false'
  ETCD_ENDPOINTS: #@ name() + "-etcd.kube-system.svc.cluster.local:2379"
---
apiVersion: v1
kind: Service
metadata:
  name: #@ controller()
  namespace: kube-system
  labels:
    app.kubernetes.io/name: #@ name()
    app.kubernetes.io/component: #@ controller()
spec:
  type: ClusterIP
  ports:
  - port: 3370
    name: rest-api
    targetPort: 3370
  selector:
    app.kubernetes.io/name: #@ name()
    app.kubernetes.io/component: #@ controller()
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: #@ controller()
  namespace: kube-system
  labels:
    app.kubernetes.io/name: #@ name()
    app.kubernetes.io/component: #@ controller()
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: #@ name()
      app.kubernetes.io/component: #@ controller()
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: #@ name()
        app.kubernetes.io/component: #@ controller()
    spec:
      priorityClassName: system-cluster-critical
      restartPolicy: Always
      dnsPolicy: ClusterFirst
      initContainers:
      - name: init
        image: #@ initimage()
        imagePullPolicy: Always
        resources:
          #! requests:
          #!   cpu: 50m
          #!   memory: 50Mi
          limits:
            cpu: 100m
            memory: 100Mi
        envFrom:
            - configMapRef:
                name: #@ controller()
        args:
            - initController
        volumeMounts:
        - name: localtime
          mountPath: /etc/localtime
        - name: init
          mountPath: /init
      containers:
      - name: controller
        image: #@ controllerimage()
        imagePullPolicy: IfNotPresent
        resources:
          #! requests:
          #!   cpu: '500m'
          #!   memory: '500Mi'
          limits:
            cpu: '1'
            memory: 1Gi
        ports:
        - name: rest-api
          containerPort: 3370
          hostPort: 3370
        - name: plain
          containerPort: 3376
          hostPort: 3376
        - name: ssl
          containerPort: 3377
          hostPort: 3377
        env:
        - name: THIS_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        #@ if name() == "piraeus":
        args:
        - startController
        - --stack-traces
        #@ end
        readinessProbe:
          successThreshold: 3
          failureThreshold: 3
          httpGet:
            port: 3370
          periodSeconds: 1
        volumeMounts:
        - name: localtime
          mountPath: /etc/localtime
        - name: init
          mountPath: /etc/linstor
          subPath: etc/linstor
        - name: log
          mountPath: /var/log/linstor-controller
      volumes:
      - name: localtime
        hostPath:
          path: /etc/localtime
      - name: init
        emptyDir: {}
      - name: log
        hostPath:
          path: #@ "/var/log/" + name() + "/linstor-controller"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              #! - key: #@ name() + "/controller"
              #!   operator: In
              #!   values:
              #!   - "true"
              - key: node-role.kubernetes.io/master
                operator: DoesNotExist
      tolerations:
      - operator: Exists
        effect: NoSchedule
      - key: CriticalAddonsOnly
        operator: Exists
      #! imagePullSecrets:
      #! - name: piraeus-regcred