#@ load("funcs.lib.yml", "map_host_linstor", "map_host_lvm", "name", "node", "initimage", "controllerhostport", "registry", "controllerimage", "satelliteimage")
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: #@ node()
  namespace: kube-system
data:
  INIT_DEBUG: 'false'
  MIN_WAIT: '5'
  MAX_WAIT: '3600'
  LS_CONTROLLERS: #@ name() + "-controller.kube-system:3370"
  DRBD_IMG_TAG: v9.0.21 #! "none" will skip drbd installation
  DRBD_IMG_PULL_POLICY: Always
  POOL_BASE_DIR: #@ "/var/local/" + name() + "/storagepools"
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: #@ node()
  namespace: kube-system
spec:
  minReadySeconds: 0
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: #@ name()
      app.kubernetes.io/component: #@ node()
  template:
    metadata:
      labels:
        app.kubernetes.io/name: #@ name()
        app.kubernetes.io/component: #@ node()
    spec:
      priorityClassName: system-node-critical
      restartPolicy: Always
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: scaler
        image: #@ initimage()
        imagePullPolicy: Always
        securityContext:
          privileged: true
        resources:
          #! requests:
          #!   cpu: 50m
          #!   memory: 50Mi
          limits:
            cpu: 100m
            memory: 100Mi
        envFrom:
        - configMapRef:
            name:  #@ node()
        env:
        - name: THIS_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name 
        - name: THIS_POD_UID
          valueFrom:
            fieldRef:
              fieldPath: metadata.uid         
        - name: THIS_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: THIS_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        volumeMounts:
        - name: localtime
          mountPath: /etc/localtime
        - name: init
          mountPath: /init
        - name: #@ "opt-" + name()
          mountPath: #@ "/opt/" + name()
        - name: usr-local-bin
          mountPath: /usr/local/bin
        - name: dockersock
          mountPath: /var/run/docker.sock
        - name: usr-src
          mountPath: /usr/src
        - name: lib-modules
          mountPath: /lib/modules
      volumes:
      - name: localtime
        hostPath:
          path: /etc/localtime
      - name: init
        emptyDir: {}
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock
          type: Socket
      - name: #@ "opt-" + name()
        hostPath:
          path: #@ "/opt/" + name()
      - name: #@ "var-local-" + name()
        hostPath:
          path: #@ "/var/local/" + name()
      - name: log
        hostPath:
          path: #@ "/var/log/"+ name() + "/linstor-satellite"
      - name: dev
        hostPath:
          path: /dev
      - name: run-lvm
        hostPath:
            path: /run/lvm
      - name: run-udev
        hostPath:
            path: /run/udev
      - name: usr-local-bin
        hostPath:
          path: /usr/local/bin
      - name: usr-src
        hostPath:
          path: /usr/src
      - name: lib-modules
        hostPath:
          path: /lib/modules
      #@ if map_host_lvm():
      - name: proc 
        hostPath: 
          path: /proc
      - name: run
        hostPath:            
          path: /run
      #@ end
      #@ if map_host_linstor():
      - name: etc-drbd-d
        hostPath:
          path: /etc/drbd.d
      - name: var-lib-linstor-d
        hostPath:
          path: /var/lib/linstor.d
      - name: etc-linstor
        hostPath:
          path: /etc/linstor
      #@ end
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: #@ name() + "/node"
                operator: In
                values:
                  - "true"
              - key: node-role.kubernetes.io/master
                operator: DoesNotExist
      tolerations:
      - operator: Exists
        effect: NoSchedule
      #! imagePullSecrets:
      #! - name: piraeus-regcred
