apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: piraeus-demo
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
      name: nginx
    spec:
      restartPolicy: Always
      terminationGracePeriodSeconds: 0
      containers:
      - image: docker.io/library/nginx:alpine
        imagePullPolicy: IfNotPresent
        name: nginx
        ports:
        - containerPort: 80
        command:
        - sh
        - -xc
        - |
          VOL="$( df | grep /usr/share/nginx/html | awk '{print $1,$NF}' )"
          echo "<center><h1>Demo volume: ${VOL}</h1></center>" > /usr/share/nginx/html/index.html
          nginx -g "daemon off;"
        volumeMounts:
        - name: html-root
          mountPath: /usr/share/nginx/html
        resources:
          limits:
            cpu: '100m'
            memory: '100Mi'
      volumes:
      - name: html-root
        persistentVolumeClaim:
          claimName: demo-rwo-r2
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: piraeus/node
                operator: In
                values:
                - "true"
      tolerations:
      - operator: "Exists"
        effect: "NoSchedule"
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: piraeus-demo
  labels:
    app: nginx
spec:
  type: NodePort
  ports:
    - targetPort: 80
      port: 80
      nodePort: 31279
  selector:
    app: nginx
