apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: demo-local-rwo-r1
  namespace: piraeus-demo
spec:
  storageClassName: piraeus-local-dflt-r1
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 21Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: demo-local-rwo-r2
  namespace: piraeus-demo
spec:
  storageClassName: piraeus-local-dflt-r2
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 22Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: demo-local-rwo-r3
  namespace: piraeus-demo
spec:
  storageClassName: piraeus-local-dflt-r3
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 23Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: demo-local-rwo-raw
  namespace: piraeus-demo
spec:
  storageClassName: piraeus-local-dflt-raw
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 20Gi