kind: Namespace
apiVersion: v1
metadata:
  name: piraeus-demo
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: piraeus-demo-pvc
  namespace: piraeus-demo
spec:
  storageClassName: piraeus-demo-r3
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
