apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: piraeus-demo-pvc
  namespace: default
spec:
  storageClassName: piraeus-default-r3
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
