#@ load("funcs.lib.yml", "name")
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: #@ name() + "-default-r1"
provisioner: linstor.csi.linbit.com
allowVolumeExpansion: true
reclaimPolicy: Delete
parameters:
  layerlist: drbd storage
  placementCount: "1"
  placementPolicy: AutoPlace
  allowRemoteVolumeAccess: "true"
  disklessOnRemaining: "false"
  mountOpts: noatime,discard
  storagePool: DfltStorPool
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: #@ name() + "-default-r2"
provisioner: linstor.csi.linbit.com
allowVolumeExpansion: true
reclaimPolicy: Delete
parameters:
  layerlist: drbd storage
  placementCount: "2"
  placementPolicy: AutoPlace
  allowRemoteVolumeAccess: "true"
  disklessOnRemaining: "false"
  mountOpts: noatime,discard
  storagePool: DfltStorPool
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: #@ name() + "-default-r3"
provisioner: linstor.csi.linbit.com
allowVolumeExpansion: true
reclaimPolicy: Delete
parameters:
  layerlist: drbd storage
  placementCount: "3"
  placementPolicy: AutoPlace
  allowRemoteVolumeAccess: "true"
  disklessOnRemaining: "false"
  mountOpts: noatime,discard
  storagePool: DfltStorPool
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: #@ name() + "-default-local"
provisioner: linstor.csi.linbit.com
allowVolumeExpansion: true
reclaimPolicy: Delete
parameters:
  layerlist: storage
  placementCount: "1"
  placementPolicy: AutoPlace
  allowRemoteVolumeAccess: "true"
  disklessOnRemaining: "false"
  mountOpts: noatime,discard
  storagePool: DfltStorPool
---
kind: VolumeSnapshotClass
apiVersion: snapshot.storage.k8s.io/v1alpha1
metadata:
  name: #@ name() + "-snapshot"
  namespace: kube-system
snapshotter: io.drbd.linstor-csi
