#@data/values
---
name: "piraeus"
namespace: "piraeus-system"
map_host_linstor: false
map_host_lvm: false
set_priority_class: false
registry: "quay.io/piraeusdatastore"
initversion: "v0.5.3"
contsatversion: "v1.4.2"
csiversion: "v0.7.4"
images:
  init: "piraeus-init"
  controller: "piraeus-server"
  satellite: "piraeus-server"
  csi: "piraeus-csi"